// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnwdldmyobyxpxmstubd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJud2RsZG15b2J5eHB4bXN0dWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MjgzNDksImV4cCI6MjA1NjQwNDM0OX0.R3pl5gUKBzmTd5iM8oQT5MQfz_RmTZObzUxhf2nR51s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);