// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfoenfikuppjmmontdva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmb2VuZmlrdXBwam1tb250ZHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNzAzMDQsImV4cCI6MjA1NjY0NjMwNH0.IeDc8JzQapBQpBWgIL7Hep_h0IjtbPKFES-7aPKQMoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);